<a href="https://colab.research.google.com/github/lakshyak200-pixel/Bootcamp/blob/main/S4GLA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def res(a):
  if a>=27:
    return "Pass"
  else:
    return "Fail"
res(4)

'Fail'

In [ ]:
import numpy as np

marks_array =np.array([78,63,62])

print(marks_array+10)


[88 73 72]


In [ ]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)

matrix =np.array([
    [10,20,30],
     [40,50,60]
    ])

print(matrix)

print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
#slicing?

grid = np.array([

[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
 [41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(grid[0,0])
print(grid[:0])
grid[1:4, 1:4]

11
[]


array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [ ]:
import numpy as np

data = np.array([78, 91, 55, 72, 40, 88, 98, 81, 11, 23, 78, 88, 91, 96])

highest_score = np.max(data)

high_scores = data[data > 80]
lowest_high_score = np.min(high_scores)
students_above_75 = np.sum(data > 75)

print(highest_score)
print(lowest_high_score)
print(students_above_75)

98
81
9


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving session4_dummy_students_data.csv.xls to session4_dummy_students_data.csv.xls


In [ ]:
import pandas as pd

df = pd.read_csv("session4_dummy_students_data.csv.xls")


In [ ]:
math_scores = df["math"].to_numpy()
print(math_scores)

print(type (math_scores))

print(math_scores.mean())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [ ]:
science_scores = df["science"].to_numpy()
print(science_scores)

print(type (science_scores))

print(science_scores.mean())

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]
<class 'numpy.ndarray'>
72.35


In [ ]:
english_scores = df["english"].to_numpy()
print(english_scores)

print(type (english_scores))

print(english_scores.mean())

[69 94 58 81 47 90 66 89 51 85 72 79 42 91 60 96 65 83 46 80]
<class 'numpy.ndarray'>
72.2


In [ ]:
#calculate the average score accroess the other two subjects

#filtering

#top students average more than or equal to 85

df["average"] = df[["math", "science", "english"]].mean(axis=1)

print(df[["name", "math", "science", "english", "average"]])

top_students =df [df["average"] >= 85]

print(top_students[["name", "average"]])



      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667
      name    average
1     Diya  

KeyError: 'attendance_p'

In [ ]:

# 1. Filter for low attendance (less than 75%)
low_attendance = df[df["attendance_percent"] < 75]

print("Students with Low Attendance")
print(low_attendance[["name", "attendance_percent"]])


# 2. Filter for students from Mathura and show specific columns
mathura_students = df[df["city"] == "Mathura"]

print("Students from Mathura")
print(mathura_students[["name", "city", "average"]])

Students with Low Attendance
      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66
Students from Mathura
      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000


In [ ]:
import pandas as pd
import numpy as np

# 2. Create an 'average' column using math, science, and english
df["average"] = df[["math", "science", "english"]].mean(axis=1)

# 3. Create a 'result' column: Pass if average >= 40, otherwise Fail
df["result"] = np.where(df["average"] >= 40, "Pass", "Fail")

# 4. Print class average
class_average = df["average"].mean()
print(f"Class Average{class_average:.2f}\n")

# 5. Print highest average and lowest average
highest_avg = df["average"].max()
lowest_avg = df["average"].min()
print("Highest and Lowest Averages")
print(f"Highest Average: {highest_avg:.2f}")
print(f"Lowest Average: {lowest_avg:.2f}\n")

# 6. Print top student or students
top_students = df[df["average"] == highest_avg]
print("Top Student(s)")
print(top_students[["name", "average"]])
print("\n")

# 7. Print students with attendance below 75
low_attendance = df[df["attendance_percent"] < 75]
print("Students with Attendance Below 75%")
print(low_attendance[["name", "attendance_percent"]])
print("\n")

# 8. Print students who submitted fewer than 6 assignments
few_assignments = df[df["assignments_submitted"] < 6]
print("Students with Fewer than 6 Assignments")
print(few_assignments[["name", "assignments_submitted"]])
print("\n")

# 9. Save final output as session4_student_report.csv
output_filename = "session4_student_report.csv"
df.to_csv(output_filename, index=False)
print(f"Success! Report saved to {output_filename}")

Class Average71.35

Highest and Lowest Averages
Highest Average: 92.67
Lowest Average: 40.67

Top Student(s)
    name    average
15  Riya  92.666667


Students with Attendance Below 75%
      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66


Students with Fewer than 6 Assignments
     name  assignments_submitted
4   Rohan                      5
12    Dev                      4
18   Yash                      5


Success! Report saved to session4_student_report.csv
